version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mosaic-project-gpas-1.7.10-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    labels:
      - "service-name:gpas"
      - "service-type:db-srv"
      - "environment:test"

  wildfly:
    image: tmfev/gpas:1.7.10
    container_name: mosaic-project-gpas-1.7.10-wildfly
    links:
      - "mysql:mysqldb"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    labels:
      - "service-name:gpas"
      - "service-type:app-srv"
      - "environment:test"
    entrypoint: /bin/bash
    command: -c "./wait-for-it.sh mysql:3306 -t 120 && ./run.sh"
